name: CI

on:
  push:
    branches: [ "**" ]
    # branches: [ develop ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Docker Image
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: docker-${{ runner.os }}-jcsda/docker-gnu-openmpi-dev
        restore-keys: |
          docker-${{ runner.os }}-

    - name: Load Cached Docker Image
      run: |
        mkdir -p /tmp/.docker-cache
        if [ -f /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar ]; then
          docker load -i /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar || true
        fi

    - name: Pull or Use Cached Image
      run: |
        docker pull jcsda/docker-gnu-openmpi-dev:latest || true
        mkdir -p /tmp/.docker-cache/jcsda/
        docker save -o /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar jcsda/docker-gnu-openmpi-dev:latest

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          jcsda/docker-gnu-openmpi-dev:latest \
          /bin/bash -c "
            mkdir -p build &&
            cd build &&
            cmake .. &&
            make -j$(nproc)
          "

    - name: Print debug
      run: |
        echo "Done building"
        nccmp --version

    - name: Install nccmp from source
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          jcsda/docker-gnu-openmpi-dev:latest \
          /bin/bash -c "
            set -e -x
            apt-get update 
            apt-get install -y \
              git autoconf automake libtool \
              netcdf-bin libnetcdf-dev \
              libhdf5-dev
            git clone https://gitlab.com/remikz/nccmp.git
            cd nccmp
            autoreconf -fiv
            CPPFLAGS="-I/usr/include" \
            LDFLAGS="-L/usr/lib/x86_64-linux-gnu" \
              ./configure  --with-netcdf=/usr || cat config.log
            make -j$(nproc)
            make install
            nccmp --version
            ccache -s || true  # optional
          "

    - name: Test in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/build \
          jcsda/docker-gnu-openmpi-dev:latest \
          /bin/bash -c "
            ctest --output-on-failure
          "

